apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp #any key/value pair, should match the selector in the service
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0
