apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp #any key/value pair, should match the selector in the service

    spec:
      containers:
        - name: webapp0-5
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

--- #document separator
apiVersion: v1
kind: Pod
metadata:
  name: mqueue
  labels:
    app: mqueue

spec:
  containers:
    - name: mqueue
      image: richardchesterwood/k8s-fleetman-queue:release1
