apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010

    - name: endpoint
      port: 61616

  type: NodePort
  # in spring backend set in properties spring.activemq.broker-url=tcp://fleetman-queue:61616

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker

spec:
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080

  type: ClusterIP
#in spring app set in properties spring.activemq.broker-url=tcp://fleetman-queue:61616
#fleetman.position.queue=positionQueue
#server.port = 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway

spec:
  selector:
    app: api-gateway

  ports:
    - name: http
      port: 8080

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  #select pods
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080 #should be greater than 30thd (for local develompent, not production)

  type: NodePort #another type is ClusterIP for internal microservices, LoadBalancer type for production

